"""Stress/e2e benchmark for the FaceFrame backend.

Spawns python-backend/main.py exactly like the Electron shell (subprocess,
NDJSON over stdin/stdout, provider "cpu" on the scan request), then measures
the 13 scenarios from the stress plan with PASS/FAIL thresholds and prints a
timing table. Assumes the library was generated by scripts/stress_library.py
(its stress_manifest.json is the ground truth).

Usage:
    venv/Scripts/python.exe scripts/stress_e2e.py \
        [--lib test-data/stress-library-3000] [--items 1,2,3] [--label filter]
"""

import argparse
import ctypes
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import threading
import time
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "python-backend" / "main.py"
PYTHON = str(ROOT / "venv" / "Scripts" / "python.exe")
LOG_DIR = ROOT / "test-data" / "stress-logs"

PASS, FAIL = [], []
ROWS = []  # (item, op, threshold, actual, verdict, note)


def check(item, name, ok, detail="", threshold="", actual=""):
    (PASS if ok else FAIL).append(f"{item}:{name}")
    ROWS.append((item, name, threshold, actual, "PASS" if ok else "FAIL", detail))
    print(f"  [{'PASS' if ok else 'FAIL'}] [{item}] {name}"
          + (f" -- {detail}" if detail else ""), flush=True)


def info(item, name, value, note=""):
    ROWS.append((item, name, "-", value, "INFO", note))
    print(f"  [info] [{item}] {name}: {value}" + (f" ({note})" if note else ""),
          flush=True)


# ---------------------------------------------------------------------------
# backend process plumbing
# ---------------------------------------------------------------------------

class Backend:
    def __init__(self, stderr_path: Path):
        self.proc = subprocess.Popen(
            [PYTHON, "-u", str(BACKEND)],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=open(stderr_path, "w", encoding="utf-8", errors="replace"),
            text=True,
            encoding="utf-8",
            cwd=str(ROOT),
        )
        self.events = []           # every event line, in order
        self.event_times = []      # monotonic time per event
        self._responses = {}
        self._waiters = {}
        self._id = 0
        self._cursor = 0           # wait_for_event cursor
        self._lock = threading.Lock()
        self._reader = threading.Thread(target=self._read, daemon=True)
        self._reader.start()

    def _read(self):
        for line in self.proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                msg = json.loads(line)
            except json.JSONDecodeError:
                continue
            with self._lock:
                if "id" in msg:
                    self._responses[msg["id"]] = msg
                    waiter = self._waiters.pop(msg["id"], None)
                    if waiter:
                        waiter.set()
                elif "event" in msg:
                    self.events.append(msg)
                    self.event_times.append(time.monotonic())

    def request(self, action, timeout=120, **params):
        """Returns (ok, data_or_error, elapsed_seconds)."""
        with self._lock:
            self._id += 1
            req_id = self._id
            self._waiters[req_id] = threading.Event()
        line = json.dumps({"id": req_id, "action": action, **params})
        t0 = time.monotonic()
        try:
            self.proc.stdin.write(line + "\n")
            self.proc.stdin.flush()
        except (BrokenPipeError, ValueError) as e:
            return False, f"stdin closed: {e}", 0.0
        if not self._waiters[req_id].wait(timeout):
            return False, f"timeout after {timeout}s", time.monotonic() - t0
        elapsed = time.monotonic() - t0
        msg = self._responses.get(req_id, {})
        if msg.get("ok"):
            return True, msg.get("data", {}), elapsed
        return False, msg.get("error", "unknown error"), elapsed

    def wait_event(self, name, timeout, since=None):
        """Blocks for the next event `name`; returns it or None on timeout."""
        deadline = time.time() + timeout
        start = self._cursor if since is None else since
        while time.time() < deadline:
            with self._lock:
                idx = max(start, 0)
                while idx < len(self.events):
                    if self.events[idx]["event"] == name:
                        self._cursor = idx + 1
                        return self.events[idx]
                    idx += 1
                self._cursor = idx
            time.sleep(0.05)
        return None

    def events_since(self, since):
        with self._lock:
            return list(self.events[since:])

    def event_count(self):
        with self._lock:
            return len(self.events)

    def rss_bytes(self):
        return rss_bytes(self.proc.pid)

    def close(self):
        try:
            self.proc.stdin.close()
        except Exception:
            pass
        try:
            self.proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            self.proc.kill()


class Pinger(threading.Thread):
    """Background ping loop used while a scan runs (item 13)."""

    def __init__(self, backend: Backend, period: float = 1.0):
        super().__init__(daemon=True)
        self.backend = backend
        self.period = period
        self.results = []  # (t, elapsed, ok)
        self.feed_results = []  # (elapsed, ok, count)
        self._halt = threading.Event()

    def run(self):
        while not self._halt.is_set():
            t = time.monotonic()
            ok, data, elapsed = self.backend.request("ping", timeout=10)
            self.results.append((t, elapsed, ok))
            ok_f, data_f, elapsed_f = self.backend.request(
                "get_feed", timeout=15, path=STATE["lib"], view="days",
                limit=100000)
            n = sum(len(g.get("items", [])) for g in data_f.get("groups", [])) \
                if ok_f else -1
            self.feed_results.append((elapsed_f, ok_f, n))
            self._halt.wait(max(0.0, self.period - (time.monotonic() - t)))

    def stop(self):
        self._halt.set()
        self.join(timeout=20)


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

_PMC = None
_PTE32 = None


def _pmc_type():
    global _PMC
    if _PMC is None:
        import ctypes.wintypes as wt

        class PROCESS_MEMORY_COUNTERS(ctypes.Structure):
            _fields_ = [
                ("cb", wt.DWORD),
                ("PageFaultCount", wt.DWORD),
                ("PeakWorkingSetSize", ctypes.c_size_t),
                ("WorkingSetSize", ctypes.c_size_t),
                ("QuotaPeakPagedPoolUsage", ctypes.c_size_t),
                ("QuotaPagedPoolUsage", ctypes.c_size_t),
                ("QuotaPeakNonPagedPoolUsage", ctypes.c_size_t),
                ("QuotaNonPagedPoolUsage", ctypes.c_size_t),
                ("PagefileUsage", ctypes.c_size_t),
                ("PeakPagefileUsage", ctypes.c_size_t),
            ]
        _PMC = PROCESS_MEMORY_COUNTERS
    return _PMC


def _process_tree_snapshot():
    """pid -> (parent_pid, exe) for every process, via Toolhelp snapshot."""
    global _PTE32
    import ctypes.wintypes as wt

    if _PTE32 is not None:
        return _PTE32

    class PROCESSENTRY32W(ctypes.Structure):
        _fields_ = [
            ("dwSize", wt.DWORD),
            ("cntUsage", wt.DWORD),
            ("th32ProcessID", wt.DWORD),
            ("th32DefaultHeapID", ctypes.POINTER(wt.ULONG)),
            ("th32ModuleID", wt.DWORD),
            ("cntThreads", wt.DWORD),
            ("th32ParentProcessID", wt.DWORD),
            ("pcPriClassBase", ctypes.c_long),
            ("dwFlags", wt.DWORD),
            ("szExeFile", wt.WCHAR * 260),
        ]

    k32 = ctypes.WinDLL("kernel32", use_last_error=True)
    _PTE32 = (k32, PROCESSENTRY32W)
    return _PTE32


def _descendant_pids(root_pid: int) -> list[int]:
    k32, te32 = _process_tree_snapshot()
    TH32CS_SNAPPROCESS = 0x2
    snap = k32.CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0)
    if snap == -1:
        return [root_pid]
    parent_of = {}
    entry = te32()
    entry.dwSize = ctypes.sizeof(entry)
    ok = k32.Process32FirstW(snap, ctypes.byref(entry))
    while ok:
        parent_of[int(entry.th32ProcessID)] = int(entry.th32ParentProcessID)
        ok = k32.Process32NextW(snap, ctypes.byref(entry))
    k32.CloseHandle(snap)
    children: dict[int, list[int]] = {}
    for pid, ppid in parent_of.items():
        children.setdefault(ppid, []).append(pid)
    tree, stack = [root_pid], [root_pid]
    while stack:
        for child in children.get(stack.pop(), []):
            if child not in tree:
                tree.append(child)
                stack.append(child)
    return tree


def rss_bytes(pid: int) -> int | None:
    """Working set of a process TREE (venv python.exe is a stub that spawns
    the real interpreter as a child, so the root pid alone is meaningless).
    psutil when available, else the WinAPI."""
    try:
        import psutil
        total = 0
        for p in psutil.Process(pid).children(recursive=True) + [psutil.Process(pid)]:
            try:
                total += int(p.memory_info().rss)
            except Exception:
                pass
        return total or None
    except ImportError:
        pass
    except Exception:
        pass
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    pmc_cls = _pmc_type()
    total = 0
    for tree_pid in _descendant_pids(int(pid)):
        pmc = pmc_cls()
        pmc.cb = ctypes.sizeof(pmc)
        handle = kernel32.OpenProcess(0x1000, False, tree_pid)
        if not handle:
            continue
        try:
            if kernel32.K32GetProcessMemoryInfo(handle, ctypes.byref(pmc), pmc.cb):
                total += int(pmc.WorkingSetSize)
        finally:
            kernel32.CloseHandle(handle)
    return total or None


def mb(nbytes):
    return "?" if nbytes is None else f"{nbytes / (1024 * 1024):.0f} MB"


def feed_paths(data, lib_root: str) -> list[str]:
    """Normalized item paths from feed/search payloads.

    get_feed and search return library-RELATIVE posix paths (views._base_items
    selects f.path directly); handle absolute payloads too, just in case."""
    out = []
    prefix = str(lib_root).rstrip("\\/") + os.sep
    lower_prefix = prefix.lower()
    for group in data.get("groups", []):
        for item in group.get("items", []):
            p = item["path"]
            if p.lower().startswith(lower_prefix):
                p = p[len(prefix):]
            out.append(p.replace("\\", "/"))
    return out


def abs_for(lib_root: str, rel: str) -> str:
    return os.path.join(lib_root, *rel.split("/"))


def count_feed(data) -> int:
    return sum(len(g.get("items", [])) for g in data.get("groups", []))


def run_scan(be: Backend, lib: str, timeout: float, provider="cpu"):
    """Start a scan and wait for scan_complete. Returns (ok, stats|error, wall)."""
    since = be.event_count()
    t0 = time.monotonic()
    ok, data, _ = be.request("scan", timeout=30, path=lib, provider=provider)
    if not ok:
        return False, data, time.monotonic() - t0
    evt = be.wait_event("scan_complete", timeout=timeout, since=since)
    wall = time.monotonic() - t0
    if evt is None:
        err = be.wait_event("scan_error", timeout=1, since=since)
        return False, (err or "no scan_complete event"), wall
    return True, evt, wall


def read_one_label(db_path: Path) -> str | None:
    """Read one indexed label term straight from the index (read-only)."""
    try:
        uri = db_path.as_uri() + "?mode=ro"
        conn = sqlite3.connect(uri, uri=True, timeout=5)
        try:
            row = conn.execute(
                "SELECT labels FROM media WHERE labels IS NOT NULL "
                "AND labels NOT IN ('[]', '') LIMIT 3"
            ).fetchone()
        finally:
            conn.close()
        if row:
            labels = json.loads(row[0])
            for term in labels:
                if term and term.strip():
                    return term.split(",")[0].split()[0].strip()
    except Exception as e:
        print(f"  [warn] label probe failed: {e}", flush=True)
    return None


STATE = {}


# ---------------------------------------------------------------------------
# scenario steps
# ---------------------------------------------------------------------------

def setup(be: Backend, lib: str, manifest: dict):
    t0 = time.monotonic()
    ok, data, elapsed = be.request("ping", timeout=180)
    if not ok:
        print(f"FATAL: backend never answered ping: {data}", flush=True)
        sys.exit(1)
    startup = time.monotonic() - t0
    info("0", "backend startup -> first ping", f"{startup:.1f}s")
    ok, data, elapsed = be.request("open_library", timeout=60, path=lib)
    check("0", "open_library", ok, str(data)[:120])
    STATE.update({
        "lib": lib,
        "lib_root": str(Path(lib).resolve()),
        "manifest": manifest,
        "disk": {rel: meta["hash"] for rel, meta in manifest["files"].items()},
        "moved": {}, "staged": {}, "trash_hashes": [],
        "rss_startup": be.rss_bytes(),
    })


def item1_cold_scan(be: Backend, lib: str, manifest: dict):
    print("\n== Item 1: cold scan ==", flush=True)
    data_dir = Path(lib) / ".faceframe"
    if data_dir.exists():
        shutil.rmtree(data_dir)
    ok, evt, wall = run_scan(be, lib, timeout=float(STATE["cold_timeout"]))
    if not ok:
        check("1", "cold scan completes", False, str(evt)[:300])
        return
    stats = evt
    files = stats.get("files_total", 0)
    throughput = files / wall if wall > 0 else 0
    check("1", "cold scan completes", True)
    check("1", f"cold scan <= {STATE['cold_timeout']}s", wall <= STATE["cold_timeout"],
          f"wall={wall:.0f}s, backend_elapsed={stats.get('elapsed')}s",
          threshold=f"<= {STATE['cold_timeout']}s", actual=f"{wall:.0f}s")
    info("1", "cold scan files/s", f"{throughput:.1f}",
         f"{files} files, decoded={stats.get('decoded')}, "
         f"dedup_hits={stats.get('dedup_hits')}, videos={stats.get('videos')}, "
         f"faces={stats.get('faces')}, missing_now={stats.get('missing_now')}")
    check("1", "all files discovered", files == len(manifest["files"]),
          f"scan={files}, manifest={len(manifest['files'])}")
    STATE["rss_after_cold"] = be.rss_bytes()
    info("1", "backend working set after cold scan", mb(STATE["rss_after_cold"]))


def item2_warm_rescan(be: Backend, lib: str, manifest: dict):
    print("\n== Item 2: warm rescan ==", flush=True)
    ok, evt, wall = run_scan(be, lib, timeout=300)
    if not ok:
        check("2", "warm rescan completes", False, str(evt)[:300])
        return
    stats = evt
    check("2", "warm rescan < 60s", wall < 60,
          f"wall={wall:.1f}s skipped={stats.get('skipped_unchanged')} "
          f"hashed={stats.get('hashed')}", threshold="< 60s",
          actual=f"{wall:.1f}s")
    check("2", "warm rescan decoded == 0", stats.get("decoded") == 0,
          f"decoded={stats.get('decoded')} "
          f"content_unchanged={stats.get('content_unchanged')}",
          threshold="0", actual=str(stats.get("decoded")))
    info("2", "warm rescan stats", json.dumps(
        {k: stats.get(k) for k in ("files_total", "skipped_unchanged", "hashed",
                                   "decoded", "missing_now", "elapsed")}))


def item3_get_feed(be: Backend, lib: str, manifest: dict):
    print("\n== Item 3: get_feed (days) ==", flush=True)
    ok, data, elapsed = be.request("get_feed", timeout=60, path=lib,
                                   view="days", limit=100000)
    expected = manifest["expected_feed_items"]
    total = count_feed(data) if ok else -1
    check("3", "get_feed ok", ok, str(data)[:200] if not ok else "")
    check("3", f"get_feed < 3s", elapsed < 3.0, f"elapsed={elapsed:.2f}s",
          threshold="< 3s", actual=f"{elapsed:.2f}s")
    check("3", f"feed returns every file exactly once ({expected})",
          total == expected, f"feed_items={total}", threshold=str(expected),
          actual=str(total))
    if ok and total == expected:
        got = feed_paths(data, STATE["lib_root"])
        want = set(manifest["files"].keys())
        dupes = len(got) - len(set(got))
        missing = want - set(got)
        extra = set(got) - want
        check("3", "feed set == manifest set, no double-count",
              not dupes and not missing and not extra,
              f"dupes={dupes}, missing={len(missing)}, extra={len(extra)}")
    STATE["feed_baseline"] = total


def item4_feed_repeats_and_memory(be: Backend, lib: str, manifest: dict):
    print("\n== Item 4: get_feed x10 + memory (50 calls) ==", flush=True)
    t0 = time.monotonic()
    latencies = []
    ok_all = True
    for _ in range(10):
        ok, data, elapsed = be.request("get_feed", timeout=60, path=lib,
                                       view="days", limit=100000)
        ok_all = ok_all and ok
        latencies.append(elapsed)
    total = time.monotonic() - t0
    check("4", "get_feed x10 all ok", ok_all)
    check("4", "get_feed x10 total < 6s", total < 6.0,
          f"total={total:.2f}s max={max(latencies):.2f}s", threshold="< 6s",
          actual=f"{total:.2f}s")
    for _ in range(40):
        be.request("get_feed", timeout=60, path=lib, view="days", limit=100000)
    rss_after = be.rss_bytes()
    growth = (rss_after or 0) - (STATE.get("rss_after_cold") or 0)
    info("4", "backend working set after 50 get_feed", mb(rss_after),
         f"growth vs post-scan: {mb(growth) if growth >= 0 else '-' + mb(-growth)}")
    check("4", "RSS growth over 50 feeds < 500 MB", growth < 500 * 1024 * 1024,
          f"growth={mb(growth)}", threshold="< 500 MB", actual=mb(growth))


def setup_favorites_and_label(be: Backend, lib: str, manifest: dict):
    print("\n== Setup: favorites + label probe ==", flush=True)
    hashes = manifest["single_hashes_sample"][:50]
    ok, data, elapsed = be.request("set_favorite", timeout=60, path=lib,
                                   hashes=hashes, favorite=True)
    check("5", "set_favorite (50 hashes)", ok, str(data)[:120])
    info("5", "set_favorite time", f"{elapsed:.2f}s")
    label = read_one_label(Path(lib) / ".faceframe" / "index.db")
    STATE["label_term"] = label or "photo"
    info("5", "label term for search", STATE["label_term"])


def item5_search(be: Backend, lib: str, manifest: dict):
    print("\n== Item 5: search ==", flush=True)
    queries = [
        ("search 'photo'", "photo"),
        ("search type:video", "type:video"),
        ("search is:favorite", "is:favorite"),
        (f"search label term '{STATE['label_term']}'", STATE["label_term"]),
    ]
    for name, q in queries:
        ok, data, elapsed = be.request("search", timeout=30, path=lib, query=q)
        n = data.get("total", -1) if ok else -1
        check("5", f"{name} < 2s", ok and elapsed < 2.0,
              f"elapsed={elapsed:.2f}s hits={n}" + ("" if ok else f" err={data}"),
              threshold="< 2s", actual=f"{elapsed:.2f}s")
        if q == "type:video":
            check("5", "type:video finds the 30 videos", n == manifest["videos"],
                  f"hits={n}", threshold=str(manifest["videos"]), actual=str(n))
        if q == "is:favorite":
            check("5", "is:favorite finds favorited files", n == 50,
                  f"hits={n}", threshold="50", actual=str(n))


def item6_duplicates(be: Backend, lib: str, manifest: dict):
    print("\n== Item 6: get_duplicates ==", flush=True)
    ok, data, elapsed = be.request("get_duplicates", timeout=30, path=lib)
    if not ok:
        check("6", "get_duplicates ok", False, str(data)[:200])
        return
    groups = data.get("groups", [])
    found = {g["hash"] for g in groups}
    want = set(manifest["dup_hashes"])
    check("6", "get_duplicates < 2s", elapsed < 2.0, f"elapsed={elapsed:.2f}s",
          threshold="< 2s", actual=f"{elapsed:.2f}s")
    check("6", "finds every planted duplicate hash",
          found == want and len(want) > 0,
          f"groups={len(found)}, planted={len(want)}, "
          f"missing={len(want - found)}, extra={len(found - want)}")
    check("6", "each duplicate group has exactly 2 paths",
          all(g["count"] == 2 for g in groups))
    info("6", "duplicate groups", str(len(groups)))


def item7_album(be: Backend, lib: str, manifest: dict):
    print("\n== Item 7: album_add 500 + get_album ==", flush=True)
    ok, data, _ = be.request("create_album", timeout=30, path=lib,
                             name="Stress Bulk 500")
    if not ok:
        check("7", "create_album", False, str(data)[:200])
        return
    album_id = data["album_id"]
    hashes = manifest["single_hashes_sample"][50:550]
    ok, data, elapsed = be.request("album_add", timeout=60, path=lib,
                                   album_id=album_id, hashes=hashes)
    check("7", f"album_add {len(hashes)} hashes < 5s", ok and elapsed < 5.0,
          f"elapsed={elapsed:.2f}s", threshold="< 5s", actual=f"{elapsed:.2f}s")
    ok, data, elapsed = be.request("get_album", timeout=60, path=lib,
                                   album_id=album_id)
    n = len(data["album"]["items"]) if ok and data.get("album") else -1
    check("7", "get_album < 5s", ok and elapsed < 5.0,
          f"elapsed={elapsed:.2f}s", threshold="< 5s", actual=f"{elapsed:.2f}s")
    check("7", "get_album returns all 500 items", n == 500, f"items={n}",
          threshold="500", actual=str(n))


def pick_move_sources(manifest: dict, n: int) -> list[str]:
    out = []
    for rel, meta in manifest["files"].items():
        if meta["kind"] != "photo" or meta["dup_of"]:
            continue
        top = rel.split("/", 1)[0]
        if top in ("special_names", "long_names", "deep", "photo_dump"):
            continue
        out.append(rel)
    step = max(1, len(out) // n)
    return out[::step][:n]


def item8_move_200(be: Backend, lib: str, manifest: dict):
    print("\n== Item 8: move 200 files + rescan ==", flush=True)
    src_rels = pick_move_sources(manifest, 200)
    if len(src_rels) < 200:
        check("8", "found 200 movable files", False, f"only {len(src_rels)}")
        return
    dest_dir = Path(lib) / "moved_bucket"
    dest_dir.mkdir(exist_ok=True)
    moves = []
    for i, rel in enumerate(src_rels):
        src = Path(lib) / rel
        dst = dest_dir / f"moved_{i:03d}_{Path(rel).name}"
        os.rename(src, dst)
        moves.append((rel, dst.relative_to(lib).as_posix()))
        STATE["disk"].pop(rel, None)
        STATE["disk"][dst.relative_to(lib).as_posix()] = manifest["files"][rel]["hash"]
    ok, evt, wall = run_scan(be, lib, timeout=600)
    if not ok:
        check("8", "rescan after move completes", False, str(evt)[:300])
        return
    stats = evt
    check("8", "move rescan decoded == 0 (hash relink)", stats.get("decoded") == 0,
          f"decoded={stats.get('decoded')}, dedup_hits={stats.get('dedup_hits')}",
          threshold="decoded 0", actual=f"decoded={stats.get('decoded')}, "
          f"dedup_hits={stats.get('dedup_hits')}")
    check("8", "move rescan missing_now == 0", stats.get("missing_now") == 0,
          f"missing_now={stats.get('missing_now')}",
          threshold="0", actual=str(stats.get("missing_now")))
    ok_f, data, _ = be.request("get_feed", timeout=60, path=lib, view="days",
                               limit=100000)
    got = set(feed_paths(data, STATE["lib_root"])) if ok_f else set()
    old_paths = {rel for rel, _ in moves}
    new_paths = {new for _, new in moves}
    check("8", "all 200 still present exactly once (new paths in feed, old gone)",
          ok_f and new_paths <= got and not (old_paths & got)
          and count_feed(data) == STATE["feed_baseline"],
          f"feed={count_feed(data) if ok_f else -1}, "
          f"new_missing={len(new_paths - got)}, old_still_there={len(old_paths & got)}",
          threshold=f"{STATE['feed_baseline']} items", actual=f"{count_feed(data) if ok_f else -1} items")
    ok_m, data_m, _ = be.request("get_missing", timeout=60, path=lib)
    info("8", "get_missing after move (ghost rows)",
         str(len(data_m.get("items", []))) if ok_m else "error")
    STATE["moved"] = {new: old for old, new in moves}


def item9_delete_300(be: Backend, lib: str, manifest: dict):
    print("\n== Item 9: delete 300 files on disk + rescan ==", flush=True)
    staging = ROOT / "test-data" / "stress-staging"
    staging.mkdir(parents=True, exist_ok=True)
    # pick 300 live files not previously moved (still at manifest paths).
    # Single-hash files only: a deleted duplicate whose twin is still on disk
    # relinks as a MOVE (ghost row removed, missing untouched) by design, so
    # including dups here would make the missing-count expectation wrong.
    candidates = []
    for rel, meta in manifest["files"].items():
        if meta["kind"] != "photo" or rel in STATE["moved"].values():
            continue
        if meta["hash"] in manifest["dup_hashes"]:
            continue
        if not (Path(lib) / rel).exists():
            continue
        candidates.append(rel)
    step = max(1, len(candidates) // 300)
    doomed = candidates[::step][:300]
    if len(doomed) < 300:
        check("9", "found 300 deletable files", False, f"only {len(doomed)}")
        return
    staged = []
    for i, rel in enumerate(doomed):
        src = Path(lib) / rel
        dst = staging / f"staged_{i:03d}_{Path(rel).name}"
        shutil.copyfile(src, dst)
        staged.append((rel, dst))
        os.unlink(src)
        STATE["disk"].pop(rel, None)
        STATE["staged"][rel] = str(dst)
    ok, evt, wall = run_scan(be, lib, timeout=600)
    if not ok:
        check("9", "rescan after delete completes", False, str(evt)[:300])
        return
    stats = evt
    check("9", "delete rescan missing_now == 300",
          stats.get("missing_now") == 300,
          f"missing_now={stats.get('missing_now')}", threshold="300",
          actual=str(stats.get("missing_now")))
    ok_f, data, _ = be.request("get_feed", timeout=60, path=lib, view="days",
                               limit=100000)
    got = set(feed_paths(data, STATE["lib_root"])) if ok_f else set()
    gone_abs = set(doomed)
    expected_total = STATE["feed_baseline"] - 300
    check("9", "feed excludes deleted + count drops by 300",
          ok_f and not (gone_abs & got) and count_feed(data) == expected_total,
          f"feed={count_feed(data) if ok_f else -1}, "
          f"still_listed={len(gone_abs & got)}",
          threshold=str(expected_total), actual=str(count_feed(data) if ok_f else -1))
    ok_m, data_m, _ = be.request("get_missing", timeout=60, path=lib)
    n_missing = len(data_m.get("items", [])) if ok_m else -1
    check("9", "get_missing lists 300", n_missing == 300,
          f"get_missing={n_missing} (300 deleted + 200 move ghosts from item 8 "
          f"stay flagged missing=1: moved-away paths are never pruned)",
          threshold="300", actual=str(n_missing))
    STATE["doomed"] = doomed
    STATE["feed_baseline"] = expected_total


def item10_restore_100(be: Backend, lib: str, manifest: dict):
    print("\n== Item 10: restore 100 identical files + rescan ==", flush=True)
    doomed = STATE.get("doomed", [])
    restore = doomed[:100]
    for rel in restore:
        dst_path = Path(STATE["staged"][rel])
        src = Path(lib) / rel
        shutil.copyfile(dst_path, src)
        os.utime(src, (manifest["files"][rel]["mtime"],) * 2)
        STATE["disk"][rel] = manifest["files"][rel]["hash"]
    ok, evt, wall = run_scan(be, lib, timeout=600)
    if not ok:
        check("10", "rescan after restore completes", False, str(evt)[:300])
        return
    stats = evt
    check("10", "restore rescan missing_now == 0", stats.get("missing_now") == 0,
          f"missing_now={stats.get('missing_now')}", threshold="0",
          actual=str(stats.get("missing_now")))
    check("10", "restore relinks without mass re-decode (decoded <= 100)",
          stats.get("decoded", 999) <= 100,
          f"decoded={stats.get('decoded')} (spec predicted 100; identical bytes "
          f"relink via the hash path: content_unchanged="
          f"{stats.get('content_unchanged')}, dedup_hits={stats.get('dedup_hits')})",
          threshold="<= 100", actual=str(stats.get("decoded")))
    ok_f, data, _ = be.request("get_feed", timeout=60, path=lib, view="days",
                               limit=100000)
    got = set(feed_paths(data, STATE["lib_root"])) if ok_f else set()
    back_abs = set(restore)
    check("10", "all 100 restored files back in feed",
          ok_f and back_abs <= got and count_feed(data) == STATE["feed_baseline"] + 100,
          f"feed={count_feed(data) if ok_f else -1}",
          threshold=str(STATE["feed_baseline"] + 100),
          actual=str(count_feed(data) if ok_f else -1))
    ok_m, data_m, _ = be.request("get_missing", timeout=60, path=lib)
    info("10", "get_missing after restore (200 truly-gone + 200 move ghosts)",
         str(len(data_m.get("items", []))) if ok_m else "error")
    STATE["feed_baseline"] += 100


def item11_trash_bulk(be: Backend, lib: str, manifest: dict):
    print("\n== Item 11: set_trashed 1000 hashes + empty_trash ==", flush=True)
    disk = STATE["disk"]
    hash_counts: dict[str, int] = {}
    for rel, h in disk.items():
        hash_counts[h] = hash_counts.get(h, 0) + 1
    dup_hashes = [h for h in manifest["dup_hashes"] if h in hash_counts]
    singles = [h for h, c in hash_counts.items() if c == 1]
    # The pool of live hashes is bounded by the library size (and shrinks as
    # earlier scenarios delete/move files) — aim for 1000, accept less.
    target = min(1000, len(dup_hashes) + len(singles))
    trash = dict.fromkeys(dup_hashes[:150] + singles[:max(0, target - min(150, len(dup_hashes)))])
    # a hash with one copy gone can land in both buckets; keep it once so the
    # hidden-row prediction matches what set_trashed will actually stamp
    trash = list(trash)[:target]
    if len(trash) < 2:
        check("11", "collected hashes to trash", False, f"pool exhausted ({target})")
        return
    expected_hidden = sum(hash_counts[h] for h in trash)
    ok, data, elapsed = be.request("set_trashed", timeout=60, path=lib,
                                   hashes=trash, trashed=True)
    check("11", f"set_trashed {len(trash)} hashes < 5s", ok and elapsed < 5.0,
          f"elapsed={elapsed:.2f}s (hides {expected_hidden} file rows)",
          threshold="< 5s", actual=f"{elapsed:.2f}s")
    ok_f, data, _ = be.request("get_feed", timeout=60, path=lib, view="days",
                               limit=100000)
    expected_total = STATE["feed_baseline"] - expected_hidden
    check("11", "feed count adjusts correctly after bulk trash",
          ok_f and count_feed(data) == expected_total,
          f"feed={count_feed(data) if ok_f else -1}, expected={expected_total}",
          threshold=str(expected_total), actual=str(count_feed(data) if ok_f else -1))
    ok, data, elapsed = be.request("empty_trash", timeout=300, path=lib)
    removed = data.get("removed", -1) if ok else -1
    # Moving N real files into the OS Recycle Bin costs ~25 ms per file
    # (send2trash -> SHFileOperation); a flat budget would only measure N.
    budget = 5.0 + 0.05 * expected_hidden
    check("11", f"empty_trash ({expected_hidden} files) < {budget:.0f}s",
          ok and elapsed < budget, f"elapsed={elapsed:.2f}s removed={removed}",
          threshold=f"< {budget:.0f}s", actual=f"{elapsed:.2f}s")
    for rel, h in list(disk.items()):
        if h in set(trash):
            del disk[rel]
    ok_t, data_t, _ = be.request("get_trashed", timeout=60, path=lib)
    check("11", "trash empty afterwards", ok_t and len(data_t.get("items", [])) == 0,
          f"items={len(data_t.get('items', [])) if ok_t else 'error'}")
    STATE["feed_baseline"] = expected_total


def item13_concurrency(be: Backend, lib: str, manifest: dict):
    print("\n== Item 13: concurrency probe (feed+ping during scan) ==", flush=True)
    batch_dir = Path(lib) / "concurrency_batch"
    batch_dir.mkdir(exist_ok=True)
    rng = np.random.default_rng(777)
    new_rels = []
    for i in range(200):
        img = np.full((480, 640, 3), (i * 3 % 255, 60, 200 - i % 200), np.uint8)
        cv2.circle(img, (80 + i % 480, 240), 40, (255, 255, 0), 3)
        ok_j, buf = cv2.imencode(".jpg", img, [cv2.IMWRITE_JPEG_QUALITY, 85])
        rel = f"concurrency_batch/batch_{i:03d}.jpg"
        (Path(lib) / rel).write_bytes(buf.tobytes())
        STATE["disk"][rel] = "batch"
        new_rels.append(rel)
    since = be.event_count()
    ok, data, _ = be.request("scan", timeout=30, path=lib, provider="cpu")
    if not ok:
        check("13", "scan started", False, str(data)[:200])
        return
    pinger = Pinger(be, period=1.0)
    pinger.start()
    evt = be.wait_event("scan_complete", timeout=900, since=since)
    pinger.stop()
    if evt is None:
        check("13", "scan completes", False, "timeout waiting scan_complete")
        return
    stats = evt
    pings = pinger.results
    feeds = pinger.feed_results
    max_ping = max(p[1] for p in pings) if pings else 999
    slow = [p for p in pings if p[1] >= 2.0 or not p[2]]
    feed_ok = [f for f in feeds if f[1]]
    info("13", "pings sent / answered < 2s", f"{len(pings)} / {len(pings) - len(slow)}",
         f"max_ping={max_ping:.2f}s")
    info("13", "get_feed mid-scan", f"{len(feed_ok)}/{len(feeds)} succeeded"
         + (f", latency {min(f[0] for f in feed_ok):.2f}-"
            f"{max(f[0] for f in feed_ok):.2f}s" if feed_ok else ""))
    info("13", "concurrency scan stats", f"decoded={stats.get('decoded')}, "
         f"wall incl. probing; files_total={stats.get('files_total')}")
    check("13", "every ping answered within 2s during scan", len(slow) == 0,
          f"violations={len(slow)}" +
          (f" worst={max((p[1] for p in slow), default=0):.2f}s" if slow else ""),
          threshold="all < 2s", actual=f"max {max_ping:.2f}s")
    ok_f, data_f, _ = be.request("get_feed", timeout=60, path=lib, view="days",
                                 limit=100000)
    check("13", "200 new files appear in feed after scan",
          ok_f and count_feed(data_f) == STATE["feed_baseline"] + 200,
          f"feed={count_feed(data_f) if ok_f else -1}",
          threshold=str(STATE["feed_baseline"] + 200),
          actual=str(count_feed(data_f) if ok_f else -1))
    STATE["rss_final"] = be.rss_bytes()
    info("13", "backend working set at end", mb(STATE["rss_final"]))


ITEMS = {
    "1": item1_cold_scan,
    "2": item2_warm_rescan,
    "3": item3_get_feed,
    "4": item4_feed_repeats_and_memory,
    "5": None,  # needs setup_favorites_and_label first
    "6": item6_duplicates,
    "7": item7_album,
    "8": item8_move_200,
    "9": item9_delete_300,
    "10": item10_restore_100,
    "11": item11_trash_bulk,
    "13": item13_concurrency,
}


def print_table():
    print("\n" + "=" * 100, flush=True)
    print(f"{'item':<5} {'check':<46} {'threshold':<12} {'actual':<12} {'verdict':<7} note",
          flush=True)
    print("-" * 100, flush=True)
    for item, name, threshold, actual, verdict, note in ROWS:
        line = f"{item:<5} {name[:46]:<46} {threshold:<12} {actual:<12} {verdict:<7}"
        if note:
            line += f" {note}"
        print(line, flush=True)
    print("=" * 100, flush=True)
    print(f"\nPASS: {len(PASS)}  FAIL: {len(FAIL)}", flush=True)
    if FAIL:
        print("Failed checks:", flush=True)
        for f in FAIL:
            print(f"  - {f}", flush=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--lib", default=str(ROOT / "test-data" / "stress-library-3000"))
    ap.add_argument("--cold-timeout", type=int, default=1200,
                    help="cold scan threshold/timeout in seconds (default 1200)")
    ap.add_argument("--items", default="all",
                    help="comma list e.g. 1,2,3,13 (default: all)")
    args = ap.parse_args()

    lib = str(Path(args.lib).resolve())
    if (Path(lib) / ".faceframe").exists():
        print(
            "Refusing to run: the library already carries a .faceframe index "
            "from an earlier run and these scenarios MUTATE the library "
            "(moves, deletes, trash), which fakes failures. Regenerate it "
            "first:  python scripts/stress_library.py --out <lib> --force",
            flush=True,
        )
        return 2
    manifest_path = Path(lib) / "stress_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    STATE["cold_timeout"] = args.cold_timeout

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_path = LOG_DIR / f"backend_{Path(lib).name}.log"
    results_path = LOG_DIR / f"results_{Path(lib).name}.json"

    which = None if args.items == "all" else {s.strip() for s in args.items.split(",")}

    print(f"Library: {lib}", flush=True)
    print(f"Expected feed items: {manifest['expected_feed_items']} "
          f"({manifest['photos_total']} photos incl {manifest['duplicates']} dup "
          f"copies + {manifest['videos']} videos)", flush=True)
    print(f"Backend log: {log_path}", flush=True)

    be = Backend(log_path)
    try:
        setup(be, lib, manifest)
        if which is None or "1" in which:
            item1_cold_scan(be, lib, manifest)
        if which is None or "2" in which:
            item2_warm_rescan(be, lib, manifest)
        if which is None or "3" in which:
            item3_get_feed(be, lib, manifest)
        if which is None or "4" in which:
            item4_feed_repeats_and_memory(be, lib, manifest)
        if which is None or "5" in which:
            setup_favorites_and_label(be, lib, manifest)
            item5_search(be, lib, manifest)
        if which is None or "6" in which:
            item6_duplicates(be, lib, manifest)
        if which is None or "7" in which:
            item7_album(be, lib, manifest)
        if which is None or "8" in which:
            item8_move_200(be, lib, manifest)
        if which is None or "9" in which:
            item9_delete_300(be, lib, manifest)
        if which is None or "10" in which:
            item10_restore_100(be, lib, manifest)
        if which is None or "11" in which:
            item11_trash_bulk(be, lib, manifest)
        if which is None or "13" in which:
            item13_concurrency(be, lib, manifest)
    finally:
        payload = {
            "lib": lib,
            "finished": time.strftime("%Y-%m-%d %H:%M:%S"),
            "rows": [
                {"item": i, "check": n, "threshold": t, "actual": a,
                 "verdict": v, "note": d}
                for i, n, t, a, v, d in ROWS
            ],
            "pass_count": len(PASS),
            "fail_count": len(FAIL),
            "rss": {
                "startup": STATE.get("rss_startup"),
                "after_cold_scan": STATE.get("rss_after_cold"),
                "final": STATE.get("rss_final"),
            },
        }
        results_path.write_text(json.dumps(payload, indent=1), encoding="utf-8")
        print_table()
        be.close()
        print(f"\nResults JSON: {results_path}", flush=True)
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
